### PR TITLE
chore: use yarn cache

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by gajus** [comment]
Don't like to use cache in CI.

**Comment by DanielRuf** [comment]
> Don't like to use cache in CI.

Any good reasons (performance gain would be useful for faster builds).

**Comment by gajus** [comment]
Well, the main reason would be that we are not using yarn.

How is this going to help npm?

**Comment by DanielRuf** [comment]
> Well, the main reason would be that we are not using yarn.
> 
> How is this going to help npm?

Many projects use yarn, it is just used for caching `node_modules` but the other solution is more npm related. Both solutions are fast and I would prefer the solution to just cache the node_modules directory =)

This PR was meant to evaluate the performance as it can differ in many projects between both caching strategies.

**Pull request closed without merging**
